### ISSUE TITLE
Отступ слева у <hr />

### ISSUE THREAD

**Issue by dmitriy-baltak** [rusnaq/rusnaq.github.io#2]
В исходниках(в html файле) для < hr /> задать отступ слева на уровне остальных вложенных элементов.

**Comment by rusnaq** [comment]
Готово!

**Comment by dmitriy-baltak** [comment]
http://joxi.ru/n2Y8DqkF3nyWm6
Рекомендую просто воспользоваться инструментом типа 
http://www.cleancss.com/html-beautify/
http://www.cleancss.com/css-beautify/

**Comment by rusnaq** [comment]
Done!
