### ISSUE TITLE
L5: Использованный подход для задания ширины блокам неверен

### ISSUE THREAD

**Issue by dmitriy-baltak** [rusnaq/rusnaq.github.io#22]
http://joxi.ru/82QVdxYs11ZeoA
По ширине вложенные блоки не должны выходить за пределы своего родителя если это явно не предусмотрено дизайном, для того что бы это нивелировать ты использовал падинг справа у родителя, что является костылем.

**Comment by rusnaq** [comment]
Готово. Но все равно не могу понять почему если я задаю ширину инпута равной родительскому блоку, инпут все равно получается шире на 22px. И почему если инпуту задаю ширину 100% он не становится равным родительскому блоку.
