### ISSUE TITLE
Не получается застились тег content в дз по 3-4 javascript

### ISSUE THREAD

**Issue by rusnaq** [rusnaq/rusnaq.github.io#23]
https://github.com/rusnaq/rusnaq.github.io/tree/master/JavaScriptHomeWork/L3-4

**Comment by dmitriy-baltak** [comment]
В чем конкретно сложность? Добавляешь класс для content при генерации и по классу стилизуешь с помощью стилей.

**Comment by rusnaq** [comment]
Да, я так и делаю, но просто не применяется стиль. Т.е. элементы которые чайлд к этому диву как будто в него не залазят. Т.е. в inspect element они внутри дива, а в действительности див стоит отдельно и не хочет ничего знать про width, height и margin

**Comment by dmitriy-baltak** [comment]
Ясно, это происходит потому что ты задаешь не класс content, а делаешь
тег content
а это не валидный тэг, попробуй задать див с классом content.

15 декабря 2015 г., 12:37 пользователь rusnaq notifications@github.com
написал:

**Comment by rusnaq** [comment]
О, заработало, спасибо. Обновил. Перепутал с тегом main )
